export const colors = {
  primary: 'blue-600',
  primaryHover: 'blue-700',
  primaryLight: 'blue-50',
  secondary: 'gray-600',
  background: 'gray-50',
  white: 'white',
  border: 'gray-200',
  textPrimary: 'gray-900',
  textSecondary: 'gray-600',
  textMuted: 'gray-500',
  success: 'green-600',
  successBg: 'green-50',
  warning: 'yellow-600',
  warningBg: 'yellow-50',
  danger: 'red-600',
  dangerBg: 'red-50',
  info: 'blue-600',
  infoBg: 'blue-50',
}
